---
type: cnct
uniqueId: pipeline-golang-container
displayName: Golang container pipeline
description: Golang build container pipeline
apiUrl: "https://api.github.com"
org: samsung-cnct
repo: container-golang
keepDays: 10
credentials: github-access